// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivpfuljtoknjskrslxjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cGZ1bGp0b2tuanNrcnNseGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyODMzODgsImV4cCI6MjA4Njg1OTM4OH0.eccTQqVtWzCTZSsv13XshMSfk0rz3c7VqlB6cEj8ocU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});